services:
  selenium:
    image: "selenium/standalone-chrome:latest"
    ports:
      - "4444:4444"
    depends_on:
      - frontend
  frontend:
    build: ../frontend
    ports:
      - "8888:80"
    depends_on:
      - backend
  backend:
    build: ../backend
    env_file:
      - backend.env
    depends_on:
      mysql:
        condition: service_healthy
  mysql:
    build: ../mysql
    env_file:
      - mysql.env
